jenkins:
  systemMessage: "Controlled by Configuration as Code"
jobs:
  - script: >
        multibranchPipelineJob('configuration-as-code') {
        branchSources {
                git {
                id = 'configuration-as-code'
                remote('https://github.com/jenkinsci/configuration-as-code-plugin.git')
                }
      }
}
